
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:keyword
    username: sa
    password: 1234
  jpa:
    open-in-view: false
    show-sql: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000
        permittedNumberOfCallsInHalfOpenState: 4
        maxWaitDurationInHalfOpenState: 1000
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10000
    instances:
      searchBlog:
        baseConfig: default

properties:
  openapi:
    kakao: {url : "https://dapi.kakao.com/v2/search/blog", Authorization: "KakaoAK f4f86203522b4f1aa7764ac1ec110397"}
    naver: {url : "https://openapi.naver.com/v1/search/blog.json", X-Naver-Client-Id: "t5xcq1Yw1k3_MX5JhXvk", X-Naver-Client-Secret: "22rKTld2fN"}
